---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab-license-exporter
  name: gitlab-license-exporter-service
  namespace: prod-devsecops
spec:
  ports:
  - name: openmetrics
    port: 8081
    targetPort: 8081
  type: ClusterIP
  selector:
    app: gitlab-license-exporter  
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
namespace: prod-devsecops
metadata:
  labels:
    app: gitlab-license-exporter
  name: gitlab-license-exporter-sm
spec:
  endpoints:
  - interval: 30s
    port: openmetrics
    path: /metrics
  selector:
    matchLabels:
      app: gitlab-license-exporter


